name: Build all

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "选择编译类型"
        required: true
        type: choice
        default: "all"
        options:
          - "all"
          - "nowifi only"
          - "wifi only"

jobs:
  trigger-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get and filter workflows
        id: filter-workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 获取所有workflows
          response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows")
          
          # 根据输入参数设置过滤条件
          case "${{ github.event.inputs.build_type }}" in
            "all")
              filter='.workflows[] | select(.name | startswith("IPQ")) | .id'
              ;;
            "nowifi only")
              filter='.workflows[] | select(.name | startswith("IPQ") and (.name | contains("NOWIFI"))) | .id'
              ;;
            "wifi only")
              filter='.workflows[] | select(.name | startswith("IPQ") and (.name | contains("NOWIFI") | not)) | .id'
              ;;
          esac

          # 处理JSON并输出结果
          filtered_ids=$(echo "$response" | jq -r "$filter | join(\" \")")
          echo "ids=${filtered_ids}" >> $GITHUB_OUTPUT

      - name: Trigger workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "${{ steps.filter-workflows.outputs.ids }}" ]; then
            echo "没有找到匹配的workflow"
            exit 0
          fi

          for workflow_id in ${{ steps.filter-workflows.outputs.ids }}; do
            echo "正在触发 workflow ID: $workflow_id"
            curl -s -X POST \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$workflow_id/dispatches" \
              -d '{"ref":"${{ github.ref }}"}'
            sleep 1
          done
